// Package docs embeds the OpenAPI spec generated by `make swagger-gen`
// (see swag annotations in internal/api/handlers.go and cmd/api/main.go).
package docs

import _ "embed"

//go:embed swagger.json
var SwaggerJSON []byte
